POST http://localhost:5173/api/chat
Content-Type: application/json

{
  "message": "Hello, who are you?"
}

###

POST http://localhost:5173/api/search
Content-Type: application/json

{
  "query": "Find me a Kaufman"
}

###
POST http://localhost:5173/api/docs
Content-Type: application/json

{
  "query": "Tell me about nir kaufman"
}

###
POST http://localhost:5173/api/tools
Content-Type: application/json

{
  "query": "Distance between paris and london"
}
